"""Gate-3 headline proof, rendered to ``bench/GATE3_PROOF.md`` (GPU-only)."""
from __future__ import annotations

import sys
import time
from math import prod
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from dmrg_transformer.core.device import describe_device, require_cuda  # noqa: E402
from dmrg_transformer.optim import DMRGOptimizer  # noqa: E402
from dmrg_transformer.tt import TensorTrain  # noqa: E402


def main() -> None:
    device = require_cuda()
    torch.manual_seed(7)

    in_dims = [8, 8]
    out_dims = [8, 8]
    N = prod(in_dims)
    M = prod(out_dims)
    rank = 4
    batch = 512

    W_scratch = torch.randn(N, M, dtype=torch.float64, device=device)
    tt_true, _ = TensorTrain.from_dense(W_scratch, in_dims, out_dims, max_rank=rank)
    W_true = tt_true.to_dense()

    X = torch.randn(batch, N, dtype=torch.float64, device=device)
    Y = X @ W_true

    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t0 = time.perf_counter()
    W_dense = torch.linalg.lstsq(X, Y).solution
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t_dense = time.perf_counter() - t0
    mse_dense = float(torch.mean((X @ W_dense - Y) ** 2).item())

    W_init = torch.randn(N, M, dtype=torch.float64, device=device) * 0.01
    tt, _ = TensorTrain.from_dense(W_init, in_dims, out_dims, max_rank=rank)
    opt = DMRGOptimizer(max_rank=rank, lam=0.0, clamp_target=False)

    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t0 = time.perf_counter()
    mse_before = float(torch.mean((X @ tt.to_dense() - Y) ** 2).item())
    opt.sweep(tt, X, Y)
    mse_1_sweep = float(torch.mean((X @ tt.to_dense() - Y) ** 2).item())
    for _ in range(19):
        opt.sweep(tt, X, Y)
    mse_20_sweeps = float(torch.mean((X @ tt.to_dense() - Y) ** 2).item())
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t_dmrg = time.perf_counter() - t0

    tt_params = sum(c.numel() for c in tt.cores)
    ratio = mse_20_sweeps / max(mse_dense, 1e-30)

    lines = [
        "# Gate-3 Proof — TT-DMRG matches Dense Least-Squares (GPU)\n\n",
        f"**Device:** `{describe_device()}`\n\n",
        "AGENTS.md §3 Validation Gate 3: *\"The MSE of the DMRG sweep must ",
        "converge to the exact same MSE as the Dense Exact Solver.\"*\n\n",
        f"**Setup:** N={N}, M={M}, TT-rank r={rank}, batch={batch}. ",
        "Target `Y = X @ W_true` where `W_true` is generated to live on the ",
        "rank-r TT manifold.\n\n",
        "## Results\n\n",
        "| Estimator | MSE | Wall time (s) |\n",
        "| :-------- | --: | ------------: |\n",
        f"| Dense `torch.linalg.lstsq` (O(N^3), cuSOLVER) | {mse_dense:.3e} | {t_dense:.4f} |\n",
        f"| TT-DMRG initial (random init) | {mse_before:.3e} | — |\n",
        f"| TT-DMRG after 1 sweep | {mse_1_sweep:.3e} | — |\n",
        f"| TT-DMRG after 20 sweeps | {mse_20_sweeps:.3e} | {t_dmrg:.4f} |\n\n",
        f"**Parameter count:** TT={tt_params:,} vs dense={N*M:,} "
        f"({(N*M)/tt_params:.1f}× compression).\n\n",
        f"**MSE ratio (DMRG / dense):** {ratio:.3e}. ",
        "Values near 1.0 (within float64 roundoff) satisfy Gate 3.\n\n",
        "> Generated by `scripts/run_gate3_proof.py`.\n",
    ]
    out = ROOT / "bench" / "GATE3_PROOF.md"
    out.write_text("".join(lines), encoding="utf-8")
    print(f"wrote: {out}")
    print(f"dense mse  = {mse_dense:.3e}")
    print(f"dmrg mse   = {mse_20_sweeps:.3e}")
    print(f"ratio      = {ratio:.3e}")


if __name__ == "__main__":
    main()
